### ISSUE TITLE
show up "Resetting the container is not allowed when a scope is active." problem

### ISSUE THREAD

**Issue by taylor19882002** [Lakion/ApiTestCase#48] opened 2016-02-13 11:20 UTC
Hi

I try to test a simple json, but show up below message, have any idea to figure out that ?

Thanks!

PHPUnit 4.8.22 by Sebastian Bergmann and contributors.

E

Time: 525 ms, Memory: 27.00Mb

There was 1 error:

1) AppBundle\Tests\Controller\DefaultControllerTest::testGetHelloWorldResponse
Symfony\Component\DependencyInjection\Exception\LogicException: Resetting the container is not allowed when a scope is active.

/Users/xxxx/Documents/www/yyyy/app/bootstrap.php.cache:2214
/Users/xxxx/Documents/www/yyyy/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php:182
/Users/xxxx/Documents/www/yyyy/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php:192
/Users/xxxx/Documents/www/yyyy/vendor/lakion/api-test-case/src/ApiTestCase.php:112

**Comment by lchrusciel** [comment] 2016-02-13 13:53
It seems it is more symfony based issue then ATC. Can you share your code snippet and phpunit configuration? Or maybe you have it in some public repository? It is quite hard to guess what is wrong based only on stack trace.

**Comment by taylor19882002** [comment] 2016-02-13 14:52
app/phpunit.xml

<?xml version="1.0" encoding="UTF-8"?>


<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/4.1/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="bootstrap.php.cache"
>
    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>../src/*/*Bundle/Tests</directory>
            <directory>../src/*/Bundle/*Bundle/Tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist>
            <directory>../src</directory>
            <exclude>
                <directory>../src/*Bundle/Resources</directory>
                <directory>../src/*Bundle/Tests</directory>
                <directory>../src/*/*Bundle/Resources</directory>
                <directory>../src/*/*Bundle/Tests</directory>
                <directory>../src/*/Bundle/*Bundle/Resources</directory>
                <directory>../src/*/Bundle/*Bundle/Tests</directory>
            </exclude>
        </whitelist>
    </filter>
</phpunit>

**Comment by taylor19882002** [comment] 2016-02-13 14:56
running command
bin/phpunit -c app src/AppBundle/Tests/Controller/DefaultControllerTest

**Comment by lchrusciel** [comment] 2016-02-15 16:44
I have tried your configuration and everything works fine. Something has to be broken on your side. I am not able to reproduce this issue. Which operating system are you using?

**Comment by lchrusciel** [comment] 2016-02-16 08:18
Since this issue is not connected with ATC, I'm closing this one.

**Closed by lchrusciel** 2016-02-16 08:18 UTC

**Comment by taylor19882002** [comment] 2016-02-17 16:26
Finally i solved this problem, I switch php-matcher version from 2.0.0-beta to dev-master, thanks your help!

**Comment by lchrusciel** [comment] 2016-02-17 17:31
Thanks for sharing. PHP-Matcher 2.0 should be released at 22.02 so it should resolved such issues for good.
